### ISSUE TITLE
UnboundLocalError: local variable 'ev_list' referenced before assignment

### ISSUE THREAD

**Issue by GLking123** [bioinfo-biols/SEVtras#15]
Dear Dr. He,
I am trying to run a task following the instructions in the "SEVtras" tutorial. Because I only have a single sample, I used the method suggested in the tutorial and made two duplicates as my input.

Does it only apply to humans and mice, and not to other non-model species?

UnboundLocalError: local variable 'ev_list' referenced before assignment.

**Comment by RuiqiaoHe** [comment]
Yes, the sEV-characteristic gene set is not sufficient for other non-model species. Currently, SEVtras only supports human and mouse.

**Comment by GLking123** [comment]
I greatly appreciate it.
