### ISSUE TITLE
SEVtras score were all NaNs

### ISSUE THREAD

**Issue by zhangyz1997** [bioinfo-biols/SEVtras#2]
I appreciate your work on this amazing package!
I am trying to apply the package to my own research, but I encountered a problem when I ran sEV_recognizer on the [Metastatic Colorectal Cancer (mCRC) scRNA-seq dataset](https://dna-discovery.stanford.edu/publicmaterial/datasets/mCRC_scRNAseq/mCRC_scRNA_raw.zip). It does not detect any sEVs in any of the samples, and the scores in raw_SEVtras.h5ad are all NaN. I tried using both the "raw_feature_bc_matrix" and the h5ad files that I generated for each sample, but neither worked. I also tried lowering the score_t parameter, but it did not help. The logs are attached below and the h5ad files are available [here](https://mail2sysueducn-my.sharepoint.com/:u:/g/personal/zhangyzh26_mail2_sysu_edu_cn/EZQ-x_yOySVPigvil4sfb1UB5Hw6trFVez-2ftSD8JwXIQ?e=TvWrof). Is this the expected behavior? I would appreciate your feedback. Thank you!

[nohup.out.txt](https://github.com/bioinfo-biols/SEVtras/files/13611523/nohup.out.txt)

**Comment by RuiqiaoHe** [comment]
Thank you very much for your tests. In this project, some normal samples fail to detect sEVs in the Part I based on the log file. It seems that SEVtras is incompatible with this condition. If you are in a hurry to get preliminary results, a sketchy solution is that you can temporarily delete these failed samples in the input sample file for sEV recognition. And I will fix these problems in the updated version (SEVtras v0.2.7) before tomorrow.

**Comment by zhangyz1997** [comment]
Thank you for your quick replies and fixes. The problem was finally resolved in version 0.2.8.
