### ISSUE TITLE
Input data type

### ISSUE THREAD

**Issue by liangxs7015** [bioinfo-biols/SEVtras#21]
Hi, I encountered a issue when preparing the input data. I have a integrated anndata with counts but several samples lacked the features.tsv.gz, bacordes.tsv.gz, and matrix.mtx.gz files. Could the SEVtras accept the anndata.layers['counts'] or h5ad file? Or could I regenerate features.tsv.gz, bacordes.tsv.gz, and matrix.mtx.gz from the anndata per sample? Now I am trying the second approach but have not succeed yet. Thanks

**Comment by RuiqiaoHe** [comment]
Sure, SEVtras can accept h5ad files as input. You can look at test data as an example (https://github.com/bioinfo-biols/SEVtras/tree/main/tests). Corresponding code provided in Simple Example section (https://github.com/bioinfo-biols/SEVtras/blob/main/README.md).

**Comment by liangxs7015** [comment]
> Sure, SEVtras can accept h5ad files as input. You can look at test data as an example (https://github.com/bioinfo-biols/SEVtras/tree/main/tests). Corresponding code provided in Simple Example section (https://github.com/bioinfo-biols/SEVtras/blob/main/README.md).

Sincerely appreciate your quick reply to help me with this issue. I've tried to seperate my anndata according to sample ID and write them into h5ad files. However, the error 'ValueError: max() arg is an empty sequence' occured after running "SEVtras.sEV_recognizer(input_path='./SEVtras_inpput_h5ad/', sample_file='./SEVtras_inpput_h5ad/sample_file.txt', out_path='./SEVtras_output/', species='Homo',alpha=0.01, score_t='10')", as the relavant issues regarding this error have been discussed, I've changed the 'alpha', 'score_t', and 'search_UMI' into different values respectively, but the issues can not be solved. Could you please provide any clue to solve this error? 

I've checked my input h5ad files (more than 100 h5ad files) and they contains the raw count in .X after 'read_h5ad', one of my sample anndata.X is "testadata.X.toarray()
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)" 

No extra .layers is contained and the .raw.X is

'testadata.raw.X.toarray()
array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 1.3886238, ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 1.0541407, ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]], dtype=float32) '

Also, these samples are from scRNA-seq, not from snRNA-seq. Thanks again for your kind help.

**Comment by RuiqiaoHe** [comment]
The input droplet-gene matrix for SEVtras.sEV_recognizer should be the raw data; here the matrix should come from the `raw_feature_bc_matrix` directory in Cell Ranger `outs`. In addition, gene filtering and pre-processing is not also recommended for the SEVtras.sEV_recognizer (please refer to [issue18](https://github.com/bioinfo-biols/SEVtras/issues/18#issuecomment-2102179457)\).

**Comment by liangxs7015** [comment]
Does it mean that the SEVtras.sEV_recognizer can not accept the h5ad input format?

> The input droplet-gene matrix for SEVtras.sEV_recognizer should be the raw data; here the matrix should come from the `raw_feature_bc_matrix` directory in Cell Ranger `outs`. In addition, gene filtering and pre-processing is not also recommended for the SEVtras.sEV_recognizer (please refer to [issue18](https://github.com/bioinfo-biols/SEVtras/issues/18#issuecomment-2102179457)).

Thanks for your remined. I finally realized that I've previously filtered the 'low quality cell' by ‘total counts’ lower than 500 and this operation has removed any potential EV in the droplets, which caused the failure for running 'SEVtras.sEV_recognizer '. Thanks for your patience and help.
