### ISSUE TITLE
All the scores of the sEVs are the same

### ISSUE THREAD

**Issue by gstaryu** [bioinfo-biols/SEVtras#22]
First of all, thank you very much for your work! 
I attempted to use `sEV_recognizer` to identify sEVs in scRNA-seq data, but the scores of the identified sEVs are all the same. Is this a normal phenomenon? Below is a image showing the identification results of my data:
![20240622155101](https://github.com/bioinfo-biols/SEVtras/assets/103102324/ae16b6c9-e2f9-4319-b8ff-0be85aabc467)

Additionally, I used the `test2.h5ad` provided in `./tests`, and the scores of the identified sEVs are also all the same. Here are the identification results for test2.h5ad:
![20240622155411](https://github.com/bioinfo-biols/SEVtras/assets/103102324/194c3388-3963-47b2-aec5-4450b20e8cab)
In sEV_recognizer, my `predefine_threads=20`, `score_t=15`.
I look forward to your reply!

**Comment by RuiqiaoHe** [comment]
Thanks for your careful testing. This is abnormal in my attempts. Here is an example of the score in my data:
![image](https://github.com/bioinfo-biols/SEVtras/assets/34981680/02b804b9-62a4-462c-a936-057e0bb11607)
The values in the test data are the same because I generated the test dataset by replication. 
I noticed that the SEVtras scores are relatively low in your sample, which may be due to the recognition thresholds being set loosely (alpha). I think these may not be true sEV signals, but rather an artifact of the loosen threshold.

**Comment by gstaryu** [comment]
Thank you for your prompt reply. I ran `sEV_recognizer` on two other datasets. Their scores were relatively high, but for one dataset, the scores were the same(first picture), while for the other dataset, the scores were different((second picture)). Apart from the datasets, the parameters I used to run `sEV_recognizer` were the same both times.
![20240622210127](https://github.com/bioinfo-biols/SEVtras/assets/103102324/d9c40d82-d0b2-4cf4-ab37-4aa882d8bb34)

![20240622210218](https://github.com/bioinfo-biols/SEVtras/assets/103102324/1654520b-d7a4-48c1-b335-8e909947256f)

I would like to understand why such strange results occur, or if this is a normal phenomenon.

**Comment by gstaryu** [comment]
> Thanks for your careful testing. This is abnormal in my attempts. Here is an example of the score in my data: ![image](https://private-user-images.githubusercontent.com/34981680/341968650-02b804b9-62a4-462c-a936-057e0bb11607.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNjA4NzEsIm5iZiI6MTcxOTA2MDU3MSwicGF0aCI6Ii8zNDk4MTY4MC8zNDE5Njg2NTAtMDJiODA0YjktNjJhNC00NjJjLWE5MzYtMDU3ZTBiYjExNjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDEyNDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZjgwOTFjYTdmMGM1NTk4M2ExNmQwNTE4NjBjYzhjZjk3Yzc3ZjdlMmE3MWU0NmI0NzdmNDM1ZDg0NGVmNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FpfkxgIjJiyB3tFce41fCmkhBssEpG9KYQCyKzIUeVs) The values in the test data are the same because I generated the test dataset by replication. I noticed that the SEVtras scores are relatively low in your sample, which may be due to the recognition thresholds being set loosely (alpha). I think these may not be true sEV signals, but rather an artifact of the loosen threshold.

Thank you for your prompt reply. I ran sEV_recognizer on two other datasets. Their scores were relatively high, but for one dataset, the scores were the same(first picture), while for the other dataset, the scores were different((second picture)). Apart from the datasets, the parameters I used to run sEV_recognizer were the same both times.
![20240622210127](https://github.com/bioinfo-biols/SEVtras/assets/103102324/a63c51e0-05b6-4103-b3b1-766537ceff7d)

![20240622210218](https://github.com/bioinfo-biols/SEVtras/assets/103102324/b62d31ad-9761-4076-9909-7c72f409c958)

I would like to understand why such strange results occur, or if this is a normal phenomenon.

**Comment by RuiqiaoHe** [comment]
If you used the strict parameters, e.g. `score_t`='15', `alpha`=0.10, I think all detected drops would potentially be the right one.
Note: `score_t` input must be string.
