### ISSUE TITLE
Error in SEVtras.sEV_recognizer

### ISSUE THREAD

**Issue by janicewu123** [bioinfo-biols/SEVtras#26]
Dear Author, I have met some troubles when I used SEVtras.sEV_recognize to analysis my own 10x-scRNAseq file of 21 samples. Firstly, my 10x-scRNAseq data was not in standard format:
![image](https://github.com/user-attachments/assets/88d5e700-6c0c-4c34-a340-00acc336b05e)
Therefore, when I run the code (SEVtras.sEV_recognizer(input_path='./',sample_file='./sample2_file',out_path='./outputs',species='Homo',dir_origin=False,predefine_threads=20)), I got this error (KeyError: 2): 
![image](https://github.com/user-attachments/assets/47c4bd2a-7bf9-4f2e-a16f-b4d45e81ac7c)
So I manually modified the original file of 10x single-cell data, as shown in below:
![image](https://github.com/user-attachments/assets/8a92306d-83ff-41c8-a32d-684f0fda40ce)
After completing the modification, I was able to run the program successfully, but soon encountered an error of “ValueError: max() arg is an empty sequence”. 
![image](https://github.com/user-attachments/assets/c8020569-5641-4836-b073-d4168dc474d3)
As you suggested in issues #4 and #20, I first adjusted to lower the parameter 'alpha' in 0.09, 0.05, 0.01 and even 0.001, but the error still existed; Considering that the number of samples has reached 21, it should not be the reason for the small number of samples. Therefore, I suspect that the data might be snRNA-seq data, but the sequencing company reports that it is scRNA-seq data (authenticity is questionable), and it is impossible to judge based on the raw data at this time. Do you have any good method to make a preliminary judgment of the two based on 10x original data? In addition, as the sample quality is not high (mt content is too high), it is unknown whether it has an impact on SEVtras analysis? Finally, I am not sure if this problem stems from the way I modified the original 10x file or if there is some other root cause. I would appreciate any insight or suggestions you may have on resolving this error. Thank you very much for your time and help. 
In addition, in order to confirm whether there is a problem in my parameter setting, I selected the GSE234527 data set sample for testing again, and the program ran normally and the results could be obtained.

**Comment by RuiqiaoHe** [comment]
Thanks for your kind testing. In my view, the modifications you made will not affect the identification of SEVtras. 
Regarding scRNA-seq or snRNA-seq, you can test the expression of genes that should be expressed in the cytoplasm. As the high expression in MT genes, the dataset may come from scRNA-seq.
However, I am wondering if the raw data you input into SEVtras is the output file in the raw_feature_bc_matrix directory. If you are using the filtered ones, it will result in the error you encountered now.

**Comment by janicewu123** [comment]
Thanks very much for your reply! I rechecked my 10x data and found that the data provided by the company came from the filtered feature bc matrix directory. Thanks again for pointing this out!
