### ISSUE TITLE
Exception: No gene sets passed through filtering condition

### ISSUE THREAD

**Issue by Souzuko** [bioinfo-biols/SEVtras#28]
Dear developer,

Thank you so much for presenting us with such a meaningful tool both for single cell and sEV research. However, when I perform the partⅡ analysis, which is the 'ESAI calculating', I encountered such problem:

SEVtras.ESAI_calculator(adata_ev_path='SRX6726369_ev.h5ad', adata_cell_path='test_cell.h5ad', out_path='./outputs', Xraw=False, OBSsample='batch', OBScelltype='ann_level_4_transferred_label_unfiltered')

2024-10-16 20:41:28,121 No gene sets passed through filtering condition!!! Try to set min_size or max_size parameters again!
Note: check gene name, gmt format, or filtering size.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[21], line 2
      1 import SEVtras
----> 2 SEVtras.ESAI_calculator(adata_ev_path='SRX6726369_ev.h5ad', adata_cell_path='test_cell.h5ad', out_path='./outputs', Xraw=False, OBSsample='batch', OBScelltype='ann_level_4_transferred_label_unfiltered')

File ~/.local/lib/python3.11/site-packages/SEVtras/main.py:188, in ESAI_calculator(adata_ev_path, adata_cell_path, out_path, species, OBSsample, OBScelltype, OBSev, OBSMpca, cellN, Xraw, normalW, plot_cmp, save_plot_prefix, OBSMumap, size)
    186 adata_cell = read_adata(adata_cell_path, get_only=False)
    187 from .functional import deconvolver, ESAI_celltype, plot_SEVumap, plot_ESAIumap
--> 188 celltype_e_number, adata_evS, adata_com = deconvolver(adata_ev, adata_cell, species, OBSsample, OBScelltype, OBSev, OBSMpca, cellN, Xraw, normalW)
    189 ##ESAI for sample
    190 sample_ESAI = (adata_com[adata_com.obs[OBScelltype]==OBSev,].obs[OBSsample].value_counts() / adata_com[adata_com.obs[OBScelltype]!=OBSev,].obs[OBSsample].value_counts()).fillna(0)

File ~/.local/lib/python3.11/site-packages/SEVtras/functional.py:118, in deconvolver(adata_ev, adata_cell, species, OBSsample, OBScelltype, OBSev, OBSMpca, cellN, Xraw, normalW)
    115 def deconvolver(adata_ev, adata_cell, species, OBSsample='batch', OBScelltype='celltype', OBSev='sEV', OBSMpca='X_pca', cellN=10, Xraw = True, normalW=True):
    117     adata_combined = preprocess_source(adata_ev, adata_cell, OBScelltype=OBScelltype, OBSev=OBSev, Xraw = Xraw)
--> 118     gsea_pval_dat = source_biogenesis(adata_cell, species, OBScelltype=OBScelltype, Xraw = Xraw, normalW=normalW)
    119     near_neighbor_dat = near_neighbor(adata_combined, OBSsample=OBSsample, OBSev=OBSev, OBScelltype=OBScelltype, OBSMpca=OBSMpca, cellN=cellN)
    121     near_neighbor_dat['times'] = ''

File ~/.local/lib/python3.11/site-packages/SEVtras/functional.py:42, in source_biogenesis(adata_cell, species, OBScelltype, Xraw, normalW)
     39 i = adata_cell.obs[OBScelltype].cat.categories[i]
     40 gene_rank = pd.DataFrame({'exp': np.array(X_norm[adata_cell.obs[OBScelltype] == str(i), :].mean(axis=0))}, index = X_input.var_names)
---> 42 res = gp.prerank(rnk=gene_rank, gene_sets=gmt_path)
     43 terms = res.results.keys()
     44 gsea_pval.append([i, res.results[list(terms)[0]]['nes'], res.results[list(terms)[0]]['pval']])        

File ~/.local/lib/python3.11/site-packages/gseapy/__init__.py:359, in prerank(rnk, gene_sets, outdir, pheno_pos, pheno_neg, min_size, max_size, permutation_num, weighted_score_type, ascending, threads, figsize, format, graph_num, no_plot, seed, verbose, processes, *arg, **kwarg)
    339     threads = processes
    340 pre = Prerank(
    341     rnk,
    342     gene_sets,
   (...)
    357     verbose,
    358 )
--> 359 pre.run()
    360 return pre

File ~/.local/lib/python3.11/site-packages/gseapy/gsea.py:373, in Prerank.run(self)
    371 self._logger.info("Parsing data files for GSEA.............................")
    372 # filtering out gene sets and build gene sets dictionary
--> 373 gmt = self.load_gmt(gene_list=dat2.index.values, gmt=self.gene_sets)
    374 self.gmt = gmt
    375 self._logger.info(
    376     "%04d gene_sets used for further statistical testing....." % len(gmt)
    377 )

File ~/.local/lib/python3.11/site-packages/gseapy/base.py:207, in GSEAbase.load_gmt(self, gene_list, gmt)
    201 if filsets_num == len(subsets):
    202     self._logger.error(
    203         "No gene sets passed through filtering condition!!! "
    204         + "Try to set min_size or max_size parameters again!\n"
    205         + "Note: check gene name, gmt format, or filtering size."
    206     )
--> 207     raise Exception("No gene sets passed through filtering condition")
    209 # self._gmtdct = genesets_dict
    210 return genesets_dict

Exception: No gene sets passed through filtering condition

I tried many solutions including turning var_names into Ensembl ID or making them all capitalized, the problem still exists.

Just in case the information is needed, I'd like to illustrate that my adata_ev comes from raw_feature_bc_matrix of several human lung tissues through sEV recognization, which was later on divided by myself according to batch since I want to analysis each single batch insead of merging them. In the case of my problem, the sEV and cell data of SRX6726369 was analysised. And my adata_cell comes from filtered_feature_bc_matrix.h5 mapped by scArches of HLCA. I'm wondering if the cause of my above problem was due to the fact that I actually put filtered cell data into ESAI instead of raw cell data. But I already set Xraw=False, and I had some trouble understanding why raw data of adata_cell should be used since according to my impression, adata_cell needs to provide the information of cell type. Then how to include cell tyoe information in raw data since there are many non-cell droplets? Moreover, I've checked the test_cell.h5ad provided as presentation but I cannot see why it could pass the ESAI while my adata_cell cannot.

Thanks again for your great work and much appretiation for your kindness. Looking forward to your quick respond!

**Comment by RuiqiaoHe** [comment]
Thanks for your patience! Hope you have solved the problem~
