### ISSUE TITLE
Would you suggest using the raw_SEVtras.h5ad , generated by the sEV_recognizer, as the adata_cell parameter in ESAI_calculator?

### ISSUE THREAD

**Issue by kingwzun** [bioinfo-biols/SEVtras#31]
Thank you very much for your work. It has provided new insights into our research. I have a question when running ESAI_calculator.  Would you suggest using the `raw_SEVtras.h5ad` file, generated by the `sEV_recognizer` in the first step, as the input for the `adata_cell_path='./tests/test_cell.h5ad'` parameter in ESAI_calculator? Of course, `raw_SEVtras.h5ad` is the output after annotating the cell type.

**Comment by RuiqiaoHe** [comment]
It is OK to use the `raw_SEVtras.h5ad` file. However, filtering of low UMI counts should be performed. Since this file may contain both cells and cell debris, you should keep only the cell component after filtering.

**Comment by kingwzun** [comment]
Thank you for your reply. Yes, I have filtered the sEVs before use
